# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux exofs-filesystem routines.
#

obj-$(CONFIG_EXOFS_FS) += exofs.o

exofs-y := module.o dir.o file.o ialloc.o inode.o namei.o super.o sysfs.o
